// packages/vue3-todo/src/views/Finish.vue
<template>
	<div class="finish">
		<div class="card">
			<div class="card-content">
				<div class="card-content">
					<FinishItem v-for="item in finishList" :key="item.id" :finishItem="item" />
				</div>
			</div>
		</div>
	</div>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue'
import FinishItem from '../components/FinishItem.vue'
import { useStore } from '../store/index'

export default defineComponent({
	name: 'Finish',
	components: {
		FinishItem
	},
	setup() {
		const store = useStore()
		const finishList = computed(() => store.state.todoList).value.filter((item) => item.done)

		return {
			finishList
		}
	}
})
</script>

<style lang="scss">
.finish {
	max-width: 600px;
	padding: 15px;
	margin: 0 auto;
	.card {
		min-height: 400px;
		background: #ededed;
		box-shadow: 0 0 30px -5px #2c3e50;
		-webkit-box-shadow: 0 0 30px -5px #2c3e50;
	}
}
</style>

// packages/react-todo/src/pages/Finish/index.tsx
import React, { useContext } from 'react'
import { TodoItemType } from '../../store/state'
import FinishItem from '../../components/FinishItem'
import { TodoContext, TodoContextType } from '../../store'

const Finish: React.FC = () => {
	const { state } = useContext<TodoContextType>(TodoContext)
	const finishList = state.todoList.filter((item) => item.done)

	return (
		<div className="todo">
			<div className="card">
				<div className="card-content">
					{finishList.map((item: TodoItemType) => {
						return <FinishItem key={item.id} todoItem={item} />
					})}
				</div>
			</div>
		</div>
	)
}

export default Finish
