// packages/react-todo/src/pages/Todo/index.tsx
import React, { useState, useContext } from 'react'
import TodoItem from '../../components/TodoItem'
import { TodoContext, TodoContextType } from '../../store'
import { TodoItemType } from '../../store/state'
import './styles.scss'

const Todo: React.FC = () => {
	const [newItemContent, setNewItemContet] = useState('')
	const { state, dispatch } = useContext<TodoContextType>(TodoContext)

	function inputChange(e: React.ChangeEvent<HTMLInputElement>) {
		if (e.target.value) setNewItemContet(e.target.value)
	}
	function addNewTodoItem(e: React.KeyboardEvent<HTMLInputElement>) {
		if (e.code === 'Enter' && newItemContent !== '') {
			dispatch({
				type: 'NEW_TODO_ITEM',
				todoItem: {
					done: false,
					id: state.todoList.length,
					content: newItemContent
				}
			})
			setNewItemContet('')
		}
	}
	function changeTodoItem(todoItem: TodoItemType) {
		dispatch({
			type: 'UPDATE_TODO_ITEM',
			todoItem
		})
	}
	function delteTodoItem(todoItem: TodoItemType) {
		dispatch({
			type: 'DELETE_TODO_ITEM',
			todoItem
		})
	}

	return (
		<div className="todo">
			<div className="card">
				<input
					className="input"
					type="text"
					placeholder="your new todo"
					onChange={inputChange}
					onKeyUp={addNewTodoItem}
				/>
				<div className="card-content">
					{state.todoList.map((item: TodoItemType) => {
						return (
							<TodoItem key={item.id} todoItem={item} changeTodoItem={changeTodoItem} delteTodoItem={delteTodoItem} />
						)
					})}
				</div>
			</div>
		</div>
	)
}

export default Todo

// packages/vue3-todo/src/views/Todo.vue
<template>
	<div class="todo">
		<div class="card">
			<input
				class="input"
				type="text"
				placeholder="your new todo"
				v-model="newItemContent"
				@keyup.enter="addNewTodoItem"
			/>
			<div class="card-content">
				<TodoItem
					v-for="item in todoList"
					:key="item.id"
					:todoItem="item"
					@changeTodoItem="changeTodoItem"
					@delteTodoItem="delteTodoItem"
				/>
			</div>
		</div>
	</div>
</template>

<script lang="ts">
import { defineComponent, computed, ref } from 'vue'
import TodoItem from '../components/TodoItem.vue'
import { useStore } from '../store/index'
import { TodoItemType } from '../store/state'

export default defineComponent({
	name: 'Todo',
	components: {
		TodoItem
	},
	setup() {
		let newItemContent = ref('')
		const store = useStore()
		const todoList = computed(() => store.state.todoList)

		function addNewTodoItem() {
			store.action.addNewTodoItem({
				done: false,
				id: todoList.value.length + 1,
				content: newItemContent.value
			})
			newItemContent.value = ''
		}

		function changeTodoItem(todoItem: TodoItemType) {
			store.action.changeTodoItemStatus(todoItem)
		}

		function delteTodoItem(todoItem: TodoItemType) {
			store.action.delteTodoItem(todoItem)
		}

		return {
			todoList,
			newItemContent,
			addNewTodoItem,
			delteTodoItem,
			changeTodoItem
		}
	}
})
</script>

<style lang="scss">
.todo {
	max-width: 600px;
	padding: 15px;
	margin: 0 auto;
	.card {
		min-height: 400px;
		padding: 15px;
		background: #ededed;
		box-shadow: 0 0 30px -5px #2c3e50;
		-webkit-box-shadow: 0 0 30px -5px #2c3e50;
	}
}
@media screen and (max-width: 500px) {
	.todo .card {
		min-height: 260px;
	}
}
</style>
